<script>
 <p t="DATEINC">-3210</p>
 <p t="NOTICE1">IMPORTANT: Be sure to review Series Descriptions for PHI!!</p>
 <p t="NOTICE2">IMPORTANT: Tags inside of sequences may contain PHI.</p>
 <p t="PROFILENAME">CTP Clinical Trial Default</p>
 <p t="PROJECTNAME">Project</p>
 <p t="SITENAME">SiteName</p>
 <p t="SITEID">20201103</p>
 <p t="TRIALNAME">Trial</p>
 <p t="SUBJECT">Subject</p>
 <p t="UIDROOT">1.2.840.113654.2.70.1</p>
 <e en="T" t="00080005" n="SpecificCharacterSet">@keep()</e>
 <e en="T" t="00080008" n="ImageType">@keep()</e>
 <e en="T" t="00080012" n="InstanceCreationDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00080013" n="InstanceCreationTime">@keep()</e>
 <e en="T" t="00080014" n="InstanceCreatorUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00080016" n="SOPClassUID">@if(SOPClassUID,contains,"1.2.840.10008.5.1.4.1.1.7"){@quarantine()}{@keep()}</e>
 <e en="T" t="00080018" n="SOPInstanceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00080020" n="StudyDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00080021" n="SeriesDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00080022" n="AcquisitionDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00080023" n="ContentDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00080024" n="OverlayDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00080025" n="CurveDate">@hashdate(this,PatientID)</e>
 <e en="T" t="0008002a" n="AcquisitionDatetime">@hashdate(this,PatientID)</e>
 <e en="T" t="00080030" n="StudyTime">@keep()</e>
 <e en="T" t="00080031" n="SeriesTime">@keep()</e>
 <e en="T" t="00080032" n="AcquisitionTime">@keep()</e>
 <e en="T" t="00080033" n="ContentTime">@keep()</e>
 <e en="T" t="00080034" n="OverlayTime">@keep()</e>
 <e en="T" t="00080035" n="CurveTime">@keep()</e>
 <e en="T" t="00080050" n="AccessionNumber">@hash(this,16)</e>
 <e en="T" t="00080058" n="FailedSOPInstanceUIDList">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00080060" n="Modality">@if(Modality,matches,"SC|DOC"){@quarantine()}{@keep()}</e>
 <e en="T" t="00080070" n="Manufacturer">@keep()</e>
 <e en="T" t="00080080" n="InstitutionName">@keep()</e>
 <e en="T" t="00080090" n="ReferringPhysicianName">@empty()</e>
 <e en="T" t="0008010d" n="CodeSetExtensionCreatorUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00081030" n="StudyDescription">@keep()</e>
 <e en="T" t="0008103e" n="SeriesDescription">@keep()</e>
 <e en="T" t="00081090" n="ManufacturerModelName">@keep()</e>
 <e en="T" t="00081110" n="RefStudySeq">@process()</e>
 <e en="T" t="00081111" n="ReferencedPerformedProcedureStepSequence">@process()</e>
 <e en="T" t="00081115" n="ReferencedSeriesSequence">@process()</e>
 <e en="T" t="00081140" n="RefImageSeq">@process()</e>
 <e en="T" t="00081150" n="RefSOPClassUID">@keep()</e>
 <e en="T" t="00081155" n="RefSOPInstanceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00081195" n="TransactionUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00081199" n="ReferencedSOPSequence">@process()</e>
 <e en="T" t="00081250" n="RelatedSeriesSequence">@process()</e>
 <e en="T" t="00082111" n="DerivationDescription">@keep()</e>
 <e en="T" t="00082112" n="SourceImageSequence">@process()</e>
 <e en="T" t="00083010" n="IrradiationEventUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00089092" n="ReferencedImageEvidenceSequence">@process()</e>
 <e en="T" t="00089123" n="CreatorVersionUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00100010" n="PatientName">@integer(this,ptid,8)</e>
 <e en="T" t="00100020" n="PatientID">@hashptid(@SITEID,PatientID,10)</e>
 <e en="T" t="00100030" n="PatientBirthDate">@empty()</e>
 <e en="T" t="00100040" n="PatientSex">@keep()</e>
 <e en="T" t="00101010" n="PatientAge">@keep()</e>
 <e en="T" t="00101020" n="PatientSize">@keep()</e>
 <e en="T" t="00101030" n="PatientWeight">@keep()</e>
 <e en="T" t="00102160" n="EthnicGroup">@keep()</e>
 <e en="T" t="001021a0" n="SmokingStatus">@keep()</e>
 <e en="T" t="001021c0" n="PregnancyStatus">@keep()</e>
 <e en="T" t="001021d0" n="LastMenstrualDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00102203" n="PatientSexNeutered">@keep()</e>
 <e en="T" t="00120062" n="PatientIdentityRemoved">@always()YES</e>
 <e en="F" t="00120063" n="DeIdentificationMethod">@always()@append(){MR approved profile for anonymizing dicom data with retaining safe siemens private groups Siemens_BDO_DICOM_anonymizer_2.4 (profile=private)  [based on DICOM PS3.15 AnnexE. Details in 0012,0064]}</e>
 <e en="F" t="00120064" n="DeIdentificationMethodCodeSeq">113100/113103/113105/113107/113108/113109/113111</e>
 <e en="T" t="00181002" n="DeviceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00181012" n="DateOfSecondaryCapture">@hashdate(this,PatientID)</e>
 <e en="T" t="00181078" n="Radiopharmaceutical Start DateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00181079" n="Radiopharmaceutical Stop DateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00181200" n="DateOfLastCalibration">@remove()</e>
 <e en="T" t="00181202" n="DateTimeOfLastCalibration">@hashdate(this,PatientID)</e>
 <e en="T" t="00181400" n="AcquisitionDeviceProcessingDescription">@remove()</e>
 <e en="T" t="00184000" n="AcquisitionComments">@remove()</e>
 <e en="T" t="0018700a" n="DetectorID">@keep()</e>
 <e en="T" t="0018700c" n="DateOfLastDetectorCalibration">@hashdate(this,PatientID)</e>
 <e en="T" t="00189424" n="AcquisitionProtocolDescription">@remove()</e>
 <e en="T" t="0018a003" n="ContributionDescription">@remove()</e>
 <e en="T" t="00189074" n="FrameAcquisitionDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00189151" n="FrameReferenceDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00189369" n="SourceStartDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="0018936A" n="SourceEndDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00189516" n="StartAcquisitionDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00189517" n="EndAcquisitionDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00189701" n="DecayCorrectionDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00189804" n="ExclusionStartDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="00189919" n="InstructionPerformedDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="0018A002" n="ContributionDateTime">@hashdate(this,PatientID)</e>
 <e en="T" t="0018a003" n="ContributionDescription">@remove()</e>
 <e en="T" t="0020000d" n="StudyInstanceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="0020000e" n="SeriesInstanceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00200010" n="StudyID">@empty()</e>
 <e en="T" t="00200052" n="FrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00200200" n="SynchronizationFrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00203401" n="ModifyingDeviceID">@remove()</e>
 <e en="T" t="00203404" n="ModifyingDeviceManufacturer">@remove()</e>
 <e en="T" t="00203406" n="ModifiedImageDescription">@remove()</e>
 <e en="T" t="00204000" n="ImageComments">@remove()</e>
 <e en="T" t="00209111" n="FrameContentSequence">@process()</e>
 <e en="T" t="00209158" n="FrameComments">@remove()</e>
 <e en="T" t="00209161" n="ConcatenationUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00209164" n="DimensionOrganizationUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00209221" n="DimensionOrganizationSequence">@process()</e>
 <e en="T" t="00209222" n="DimensionIndexSequence">@process()</e>
 <e en="T" t="00280303" n="LongitudinalTemporalInformationModified">@always()MODIFIED</e>
 <e en="T" t="00281199" n="PaletteColorLUTUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00281214" n="LargePaletteColorLUTUid">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00284000" n="ImagePresentationComments">@remove()</e>
 <e en="T" t="00321000" n="ScheduledStudyStartDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00321001" n="ScheduledStudyStartTime">@keep()</e>
 <e en="T" t="00321010" n="ScheduledStudyStopDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00321011" n="ScheduledStudyStopTime">@keep()</e>
 <e en="T" t="00321040" n="StudyArrivalDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00321050" n="StudyCompletionDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00321070" n="RequestedContrastAgent">@keep()</e>
 <e en="T" t="00380020" n="AdmittingDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00380021" n="AdmittingTime">@keep()</e>
 <e en="T" t="00380030" n="DischargeDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00380032" n="DischargeTime">@keep()</e>
 <e en="T" t="00400002" n="SPSStartDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00400003" n="SPSStartTime">@keep()</e>
 <e en="T" t="00400004" n="SPSEndDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00400005" n="SPSEndTime">@keep()</e>
 <e en="T" t="00400244" n="PPSStartDate">@hashdate(this,PatientID)</e>
 <e en="T" t="00400245" n="PPSStartTime">@keep()</e>
 <e en="T" t="00400250" n="PPSEndDate">@hashdate(this,PatientID)</e>
 <e en="T" t="0040a170" n="PurposeOfReferenceCodeSequence">@process()</e>
 <e en="T" t="0040a730" n="ContentSeq">@process()</e>
 <e en="T" t="00409096" n="RealWorldValueMappingSequence">@process()</e>
 <e en="T" t="00409224" n="RealWorldValueIntercept">@keep()</e>
 <e en="T" t="00409225" n="RealWorldValueSlope">@keep()</e>
 <e en="T" t="0040db0c" n="TemplateExtensionOrganizationUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="0040db0d" n="TemplateExtensionCreatorUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00540013" n="EnergyWindowRangeSequence">@process()</e>
 <e en="T" t="00540014" n="EnergyWindowLowerLimit">@keep()</e>
 <e en="T" t="00540015" n="EnergyWindowUpperLimit">@keep()</e>
 <e en="T" t="00540016" n="RadiopharmaceuticalInformationSeq">@always()@process()</e>
 <e en="T" t="00540081" n="NumberOfSlices">@keep()</e>
 <e en="T" t="00540300" n="RadionuclideCodeSequence">@process()</e>
 <e en="T" t="00540410" n="PatientOrientationCodeSequence">@process()</e>
 <e en="T" t="00540414" n="PatientGantryRelationshipCodeSequence">@process()</e>
 <e en="T" t="00541000" n="SeriesType">@keep()</e>
 <e en="T" t="00541001" n="Units">@keep()</e>
 <e en="T" t="00541002" n="CountsSource">@keep()</e>
 <e en="T" t="00541004" n="ReprojectionMethod">@keep()</e>
 <e en="T" t="00541006" n="SUVType">@keep()</e>
 <e en="T" t="00541100" n="RandomsCorrectionMethod">@keep()</e>
 <e en="T" t="00541101" n="AttenuationCorrectionMethod">@keep()</e>
 <e en="T" t="00541102" n="DecayCorrection">@keep()</e>
 <e en="T" t="00541103" n="ReconstructionMethod">@keep()</e>
 <e en="T" t="00541104" n="DetectorLinesOfResponseUsed">@keep()</e>
 <e en="T" t="00541105" n="ScatterCorrectionMethod">@keep()</e>
 <e en="T" t="00541200" n="AxialAcceptance">@keep()</e>
 <e en="T" t="00541201" n="AxialMash">@keep()</e>
 <e en="T" t="00541202" n="TransverseMash">@keep()</e>
 <e en="T" t="00541203" n="DetectorElementSize">@keep()</e>
 <e en="T" t="00541210" n="CoincidenceWindowWidth">@keep()</e>
 <e en="T" t="00541220" n="SecondaryCountsType">@keep()</e>
 <e en="T" t="00541300" n="FrameReferenceTime">@keep()</e>
 <e en="T" t="00541310" n="PrimaryPromptsCountsAccumulated">@keep()</e>
 <e en="T" t="00541311" n="SecondaryCountsAccumulated">@keep()</e>
 <e en="T" t="00541320" n="SliceSensitivityFactor">@keep()</e>
 <e en="T" t="00541321" n="DecayFactor">@keep()</e>
 <e en="T" t="00541322" n="DoseCalibrationFactor">@keep()</e>
 <e en="T" t="00541323" n="ScatterFractionFactor">@keep()</e>
 <e en="T" t="00541324" n="DeadTimeFactor">@keep()</e>
 <e en="T" t="00541330" n="ImageIndex">@keep()</e>
 <e en="T" t="00700084" n="ContentCreatorsName">@empty()</e>
 <e en="T" t="0070031a" n="FiducialUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00880140" n="StorageMediaFilesetUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="30060002" n="StructureSetLabel">@keep()</e>
 <e en="T" t="30060004" n="StructureSetName">@keep()</e>
 <e en="T" t="30060006" n="StructureSetDescription">@keep()</e>
 <e en="T" t="30060008" n="StructureSetDate">@hashdate(this,PatientID)</e>
 <e en="T" t="30060010" n="ReferencedFrameOfReferenceSequence">@process()</e>
 <e en="T" t="30060012" n="RTReferencedStudySequence">@process()</e>
 <e en="T" t="30060014" n="RTReferencedSeriesSequence">@process()</e>
 <e en="T" t="30060016" n="ContourImageSequence">@process()</e>
 <e en="T" t="30060020" n="StructureSetROISequence">@process()</e>
 <e en="T" t="30060022" n="ROINumber">@keep()</e>
 <e en="T" t="30060024" n="ReferencedFrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="30060026" n="ROIName">@keep()</e>
 <e en="T" t="30060028" n="ROIDescription">@keep()</e>
 <e en="T" t="3006002a" n="ROIDisplayColor">@keep()</e>
 <e en="T" t="30060036" n="ROIGenerationAlgorith">@keep()</e>
 <e en="T" t="30060039" n="ROIContourSequence">@process()</e>
 <e en="T" t="30060040" n="ContourSequence">@process()</e>
 <e en="T" t="30060042" n="ContourGeometricType">@keep()</e>
 <e en="T" t="30060046" n="NumberOfContourPoints">@keep()</e>
 <e en="T" t="30060048" n="ContourNumber">@keep()</e>
 <e en="T" t="30060050" n="ContourData">@keep()</e>
 <e en="T" t="30060080" n="RTROIObservationsSequence">@process()</e>
 <e en="T" t="30060082" n="ObservationNumber">@keep()</e>
 <e en="T" t="30060084" n="ReferencedROINumber">@keep()</e>
 <e en="T" t="300600a4" n="RTROIInterpretedType">@keep()</e>
 <e en="T" t="300600c2" n="RelatedFrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="300a0013" n="DoseReferenceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="20500020" n="PresentationLUTShape">@keep()</e>
 <e en="T" t="52009229" n="SharedFunctionalGroupsSequence">@process()</e>
 <e en="T" t="52009230" n="PerFrameFunctionalGroupsSequence">@process()</e>
 <e en="T" t="00400555" n="AcquisitionContextSequence">@process()</e>   
 <e en="T" t="00089124" n="DerivationImageSequence">@process()</e>
 <e en="T" t="00089154" n="SourceImageEvidenceSequence">@process()</e>
 <e en="T" t="00400254" n="PPSDescription">@keep()</e>
 <e en="T" t="56000020" n="SpectroscopyData">@keep()</e>
 <e en="T" t="00089205" n="PixelPresentation">@keep()</e> 
 <e en="T" t="00089206" n="VolumetricProperties">@keep()</e>
 <e en="T" t="00089207" n="VolumeBasedCalculationTechnique">@keep()</e>
 <e en="T" t="00089208" n="ComplexImageComponent">@keep()</e>
 <e en="T" t="00089209" n="AcquisitionContrast">@keep()</e>
 <e en="T" t="00181202" n="DateTimeOfLastCalibration">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]28" n="Unique image iden">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]29" n="Histogram tables">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]2A" n="User defined data">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]61" n="Scanner Study Entity UID">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]62" n="Scanner Study ID">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]88" n="PURE Acquisition Calibration Series UID">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]98" n="ASSET Acquisition Calibration Series UID">@remove()</e>
 <e en="T" t="0019[GEMS_ACQU_01]9D" n="Pulse Sequence Date">@remove()</e>
 <e en="T" t="0043[GEMS_PARM_01]39" n="Diffusion b-value">@keep()</e>
 <e en="T" t="7FE1[SIEMENS MR RAW DATA]10" n="DTI Raw Data">@keep()</e>
 <e en="T" t="7FE1[SIEMENS MR IMA]10" n="DTI Raw Data">@keep()</e>
 <e en="T" t="2001[Philips Imaging DD 001]03" n="Diffusion b-value">@keep()</e>
 <k en="T" t="0018">Keep group 0018</k>
 <k en="T" t="0020">Keep group 0020</k>
 <k en="T" t="0028">Keep group 0028</k>
 <k en="T" t="safeprivateelements">Keep safe private elements</k>
 <r en="T" t="curves">Remove curves</r>
 <r en="T" t="overlays">Remove overlays</r>
 <r en="T" t="privategroups">Remove private groups</r>
 <r en="T" t="unspecifiedelements">Remove unchecked elements</r>
</script>
